name: deploy2ssh workflow
on:
  push:
    branches: main

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest

    # if: contains(github.event.head_commit.message, '__@production__')
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: afeiship/action-deploy2ssh@main
        with:
          build_dist: app
          oss_bucket: /mnt/vdb/wms.dicfree.cn/frontend/beta/