name: deploy2ssh workflow
on:
  push:
    branches: main

jobs:
  Release:
    name: Release
    runs-on: ubuntu-latest

    # if: contains(github.event.head_commit.message, '__@production__')
    steps:
      - uses: actions/checkout@v3
      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: "app/*,app/*.*"
          target: /mnt/vdb/wms.dicfree.cn/frontend/beta
          rm: true